### ISSUE TITLE
Unsupported descriptor file encoding Shift_JIS

### ISSUE THREAD

**Issue by mnrkbys** [libyal/libvmdk#23]
I have encountered a problem which is similar to the libvmdk issue #10 .
VMware Workstation on Windows Japanese edition sets "encoding" to "Shift_JIS" in "Disk Descriptor" of VMDK. But libvmdk and libclocale don't support it.
Could you support Shift_JIS as same as GBK and Big5?
By the way, Shift_JIS is mapped to cp932.

![libvmdk_not_support_shift_jis_00](https://user-images.githubusercontent.com/26597618/76057378-b7c73e80-5fbc-11ea-8427-a65b7e00cb3b.png)

**Comment by joachimmetz** [comment]
@mnrkbys, thx for the report.

> Could you support Shift_JIS as same as GBK and Big5?
I can. I'll update documentation and source as soon as time permits.

Are you aware of any edge cases where Shift_JIS would be (potentially) different from cp932?

In the mean time if you extend libvmdk/libvmdk_descriptor_file.c similar to https://github.com/libyal/libvmdk/commit/4b09bb827d9335a842ba6dd7e1e1f6cd47669504 that should get you

**Comment by mnrkbys** [comment]
Sorry, I am not familiar with character codes.
So, I don't know what is the difference between Shift_JIS and cp932.
I will try to make the patch. Thank you.

**Comment by joachimmetz** [comment]
Changes in https://github.com/libyal/libvmdk/commit/2094cdbca3cb7d11803b4a24e4d223bfab6cc80e
