### ISSUE TITLE
Build from source package requires synclibs.sh and autogen.sh?

### ISSUE THREAD

**Issue by bgrundy** [libyal/libvmdk#29]
Prior releases had a working `configure` script.  The current source tarball (`libvmdk-alpha-20210807.tar.gz`) requires `synclibs.sh` and `autoget.sh` prior to running `./configure`.  The documentation on the wiki indicates that those scripts should be used for building from git source.

Will this be a permanent change in building the source tarballs?

**Comment by joachimmetz** [comment]
> Prior releases had a working configure script. 

They never did in git, have a look at https://github.com/libyal/libvmdk/wiki/Building#read-first

**Comment by joachimmetz** [comment]
Also https://github.com/libyal/libvmdk/releases/download/20210807/libvmdk-alpha-20210807.tar.gz does contain a configure script make sure to download the right .tar.gz 

Unfortunately the git source downloads cannot be disabled
