### ISSUE TITLE
Case-sensitive descriptor section heading parsing is too strict

### ISSUE THREAD

**Issue by uckelman** [libyal/libvmdk#5]
I've come across some VMDKs which have `# The disk Data Base` as a descriptor file section header instead of `# The Disk Data Base` as specified in the spec. I don't know what's producing these, but as they are otherwise conformant images and the section headers are strictly speaking just comments, it would be nice if libvmdk would read them.

The only required change to libvmdk is to use `libcstring_narrow_string_compare_no_case` instead ` of  `libcstring_narrow_string_compare` when checking the section headings. Patch to follow.

**Comment by uckelman** [comment]
Fixed in PR #6.

**Comment by joachimmetz** [comment]
Any indication in the descriptor file that might hint to the creating tool?

**Comment by uckelman** [comment]
> Any indication in the descriptor file that might hint to the creating tool?

I've been told it was written by VirtualBox.

**Comment by uckelman** [comment]
Yes, it definitely could have come from VirtualBox. The oddly-cased header is right there in the VirtualBox source: https://www.virtualbox.org/browser/vbox/trunk/src/VBox/Storage/VMDK.cpp#L1994

**Comment by joachimmetz** [comment]
Thanks, useful info
